/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.feliperyjuanr.view;
import com.feliperyjuanr.services.ServicioEditoriales;
import com.feliperyjuanr.services.ServicioPublicaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class ActualizarLibro extends javax.swing.JFrame {
    private ServicioPublicaciones servicioPublicacion;
    private ServicioEditoriales servicioEditorial;
    private String antiguoTitulo;

    /**
     * Creates new form BuscarLibro
     */
    public ActualizarLibro(ServicioPublicaciones servicioPublicacion, ServicioEditoriales servicioEditorial) {
        this.servicioPublicacion = servicioPublicacion;
        this.servicioEditorial = servicioEditorial;
        antiguoTitulo = "";
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblTitulo6 = new javax.swing.JLabel();
        txtTituloBuscar = new javax.swing.JTextField();
        lblBuscarLibro = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEditorial = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        chxTapaDura = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        cbxEditorial = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Libro");

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 150, 243), 2, true));

        lblTitulo6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitulo6.setText("Digite el titulo del Libro:");

        lblBuscarLibro.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblBuscarLibro.setForeground(new java.awt.Color(33, 150, 243));
        lblBuscarLibro.setText("Actualizar Libro");

        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo6)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblBuscarLibro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap())
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 150, 243), 2, true));

        lblEditorial.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblEditorial.setText("Editorial");

        txtPrecio.setEditable(true);

        chxTapaDura.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        chxTapaDura.setText("Tapa Dura");
        chxTapaDura.setEnabled(true);
        chxTapaDura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxTapaDuraActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitulo.setText("Titulo");

        txtTitulo.setEditable(true);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lblAutor.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAutor.setText("Autor");

        txtAutor.setEditable(true);
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lblLibro.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblLibro.setForeground(new java.awt.Color(33, 150, 243));
        lblLibro.setText("Libro . . .");

        lblPrecio1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblPrecio1.setText("Precio");

        btnActualizar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio1)
                            .addComponent(lblEditorial))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtAutor)
                            .addComponent(txtPrecio)
                            .addComponent(cbxEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLibro)
                            .addComponent(lblAutor)
                            .addComponent(lblTitulo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chxTapaDura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorial)
                    .addComponent(cbxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(chxTapaDura)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        cbxEditorial.removeAllItems();
        
        String titulo = txtTituloBuscar.getText();
        if(servicioPublicacion.buscarLibro(titulo)!=null)
        {
            txtTitulo.setText(servicioPublicacion.buscarLibro(titulo).getTitulo());
            txtAutor.setText(servicioPublicacion.buscarLibro(titulo).getAutor());
            txtPrecio.setText(servicioPublicacion.buscarLibro(titulo).getPrecio()+"");
            antiguoTitulo = txtTituloBuscar.getText();
            
            for (int i = 0; i < servicioEditorial.listarEditoriales().size(); i++) {
                cbxEditorial.addItem(servicioEditorial.listarEditoriales().get(i).getNombre());
            }
            
            cbxEditorial.setSelectedItem(servicioPublicacion.buscarLibro(titulo).getEditorial().getNombre());
            chxTapaDura.setSelected(servicioPublicacion.buscarLibro(titulo).isTapaDura());
            btnActualizar.setEnabled(true);
            lblLibro.setForeground(new java.awt.Color(76, 175, 80));
            jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 175, 80), 2, true));
        }
        else
        {
            lblLibro.setForeground(new java.awt.Color(244, 67, 54));
            jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 67, 54), 2, true));
            cbxEditorial.setSelectedIndex(-1);
            txtTitulo.setText("");
            txtAutor.setText("");
            txtPrecio.setText("");
            chxTapaDura.setSelected(false);
            btnActualizar.setEnabled(false);
            antiguoTitulo = "";
            JOptionPane.showMessageDialog(this, "Error: No hay ningun Libro con ese Titulo!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chxTapaDuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxTapaDuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chxTapaDuraActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int respuesta = servicioPublicacion.actualizarLibro(antiguoTitulo, txtTitulo.getText(),
        txtAutor.getText(), Double.parseDouble(txtPrecio.getText()), chxTapaDura.isSelected(), servicioEditorial.buscarEditorial((String)cbxEditorial.getSelectedItem()));
        
        switch(respuesta)
            {
                case 0:
                {
                    JOptionPane.showMessageDialog(this, "Libro actualizado exitosamente!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    txtTituloBuscar.setText("");
                    txtTitulo.setText("");
                    txtAutor.setText("");
                    txtPrecio.setText("");
                    cbxEditorial.setSelectedIndex(-1);
                    chxTapaDura.setSelected(false);
                   
                    break;
                }
                case 1:
                {
                    JOptionPane.showMessageDialog(this, "Error: Campos incorrectos o precio menor a 50!", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxEditorial;
    private javax.swing.JCheckBox chxTapaDura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblBuscarLibro;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloBuscar;
    // End of variables declaration//GEN-END:variables
}
