/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.feliperyjuanr.view;

import com.feliperyjuanr.model.Editorial;
import com.feliperyjuanr.services.ServicioEditoriales;
import com.feliperyjuanr.services.ServicioPublicaciones;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
        
        

/**
 *
 * @author juanp
 */
public class GUI extends javax.swing.JFrame {
    
    private ServicioEditoriales servicioEditorial;
    private ServicioPublicaciones servicioPublicacion;
    /**
     * Creates new form GUI
     */
    public GUI() {
        servicioEditorial = new ServicioEditoriales();
        servicioPublicacion = new ServicioPublicaciones();
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btnCerrar = new javax.swing.JMenuItem();
        menuLibro = new javax.swing.JMenu();
        itemAgregarL = new javax.swing.JMenuItem();
        itemBuscarL = new javax.swing.JMenuItem();
        itemActualizarL = new javax.swing.JMenuItem();
        itemListarL = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();
        itemCalcularL = new javax.swing.JMenuItem();
        menuRevista = new javax.swing.JMenu();
        itemAgregarR = new javax.swing.JMenuItem();
        itemBuscarR = new javax.swing.JMenuItem();
        itemActualizarR = new javax.swing.JMenuItem();
        itemListarR = new javax.swing.JMenuItem();
        itemEliminarR = new javax.swing.JMenuItem();
        itemCalcularR = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemAgregarE = new javax.swing.JMenuItem();
        itemBuscarE = new javax.swing.JMenuItem();
        itemActualizarE = new javax.swing.JMenuItem();
        itemListarE = new javax.swing.JMenuItem();
        itemEliminarE = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Publicaciones");

        ImageIcon imagenLogoGOD = new ImageIcon("src/main/java/data/logoPublicacion.png");
        lblImagenLogo.setIcon(imagenLogoGOD);

        menuFile.setText("Archivo");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        menuFile.add(btnCerrar);

        jMenuBar1.add(menuFile);

        menuLibro.setText("Libro");

        itemAgregarL.setText("Agregar Libro");
        itemAgregarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarLActionPerformed(evt);
            }
        });
        menuLibro.add(itemAgregarL);

        itemBuscarL.setText("Buscar Libro");
        itemBuscarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarLActionPerformed(evt);
            }
        });
        menuLibro.add(itemBuscarL);

        itemActualizarL.setText("Actualizar Libro");
        itemActualizarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarLActionPerformed(evt);
            }
        });
        menuLibro.add(itemActualizarL);

        itemListarL.setText("Listar Libros");
        itemListarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarLActionPerformed(evt);
            }
        });
        menuLibro.add(itemListarL);

        itemEliminar.setText("Eliminar libro");
        itemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarActionPerformed(evt);
            }
        });
        menuLibro.add(itemEliminar);

        itemCalcularL.setText("Calcular Precio Libros");
        itemCalcularL.setToolTipText("");
        itemCalcularL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalcularLActionPerformed(evt);
            }
        });
        menuLibro.add(itemCalcularL);

        jMenuBar1.add(menuLibro);

        menuRevista.setText("Revista");

        itemAgregarR.setText("Agregar Revista");
        itemAgregarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarRActionPerformed(evt);
            }
        });
        menuRevista.add(itemAgregarR);

        itemBuscarR.setText("Buscar Revista");
        itemBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarRActionPerformed(evt);
            }
        });
        menuRevista.add(itemBuscarR);

        itemActualizarR.setText("Actualizar Revista");
        itemActualizarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarRActionPerformed(evt);
            }
        });
        menuRevista.add(itemActualizarR);

        itemListarR.setText("Listar Revistas");
        itemListarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarRActionPerformed(evt);
            }
        });
        menuRevista.add(itemListarR);

        itemEliminarR.setText("Eliminar Revista");
        itemEliminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarRActionPerformed(evt);
            }
        });
        menuRevista.add(itemEliminarR);

        itemCalcularR.setText("Calcular Precio Revistas");
        itemCalcularR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalcularRActionPerformed(evt);
            }
        });
        menuRevista.add(itemCalcularR);

        jMenuBar1.add(menuRevista);

        jMenu1.setText("Editorial");

        itemAgregarE.setText("Agregar Editorial");
        itemAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEActionPerformed(evt);
            }
        });
        jMenu1.add(itemAgregarE);

        itemBuscarE.setText("Buscar Editorial");
        itemBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEActionPerformed(evt);
            }
        });
        jMenu1.add(itemBuscarE);

        itemActualizarE.setText("Actualizar Editorial");
        itemActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarEActionPerformed(evt);
            }
        });
        jMenu1.add(itemActualizarE);

        itemListarE.setText("Listar Editoriales");
        itemListarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarEActionPerformed(evt);
            }
        });
        jMenu1.add(itemListarE);

        itemEliminarE.setText("Eliminar Editorial");
        itemEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEActionPerformed(evt);
            }
        });
        jMenu1.add(itemEliminarE);

        jMenuBar1.add(jMenu1);

        menuHelp.setText("Ayuda");

        btnAbout.setText("Acerca de");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        menuHelp.add(btnAbout);

        menuInfo.setText("Info Empresa");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuHelp.add(menuInfo);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        String desarrollo = "Desarrollado por:\n\n"
                + "Juan Felipe Rodriguez Barbosa\n"
                + "Cod.2220221045\n"
                + "Juan Esteban Rodriguez Castellanos\n"
                + "Cod.2220221063\n\n"
                + "Desarrollo de Aplicaciones Empresariales\n"
                + "Version 1.0";

        JOptionPane.showMessageDialog(this, desarrollo, "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void itemCalcularLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcularLActionPerformed
        // TODO add your handling code here:
        CalcularPrecioLibros calcular = new CalcularPrecioLibros(servicioPublicacion);
        calcular.setVisible(true);
    }//GEN-LAST:event_itemCalcularLActionPerformed

    private void itemAgregarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarLActionPerformed
        // TODO add your handling code here:
        AgregarLibro agregar = new AgregarLibro(servicioPublicacion,servicioEditorial);
    }//GEN-LAST:event_itemAgregarLActionPerformed

    private void itemBuscarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarLActionPerformed
        // TODO add your handling code here:
        BuscarLibro buscar = new BuscarLibro(servicioPublicacion);
        buscar.setVisible(true);
    }//GEN-LAST:event_itemBuscarLActionPerformed

    private void itemListarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarLActionPerformed
        // TODO add your handling code here:
        ListarLibros listar = new ListarLibros(servicioPublicacion);
        listar.setVisible(true);
    }//GEN-LAST:event_itemListarLActionPerformed

    private void itemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarActionPerformed
        // TODO add your handling code here:
        EliminarLibro eliminar = new EliminarLibro(servicioPublicacion);
        eliminar.setVisible(true);
    }//GEN-LAST:event_itemEliminarActionPerformed

    private void itemCalcularRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcularRActionPerformed
        // TODO add your handling code here:
        CalcularPrecioRevistas calcular = new CalcularPrecioRevistas(servicioPublicacion);
        calcular.setVisible(true);
    }//GEN-LAST:event_itemCalcularRActionPerformed

    private void itemAgregarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarRActionPerformed
        // TODO add your handling code here:
        AgregarRevista agregar = new AgregarRevista(servicioPublicacion,servicioEditorial);
        agregar.setVisible(true);
    }//GEN-LAST:event_itemAgregarRActionPerformed

    private void itemBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarRActionPerformed
        // TODO add your handling code here:
        BuscarRevista buscar = new BuscarRevista(servicioPublicacion);
        buscar.setVisible(true);
    }//GEN-LAST:event_itemBuscarRActionPerformed

    private void itemListarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarRActionPerformed
        // TODO add your handling code here:
        ListarRevistas listar = new ListarRevistas(servicioPublicacion);
        listar.setVisible(true);
    }//GEN-LAST:event_itemListarRActionPerformed

    private void itemEliminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarRActionPerformed
        // TODO add your handling code here:
        EliminarRevista eliminar = new EliminarRevista(servicioPublicacion);
        eliminar.setVisible(true);
    }//GEN-LAST:event_itemEliminarRActionPerformed

    private void itemAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEActionPerformed
        // TODO add your handling code here:
        AgregarEditorial agregar = new AgregarEditorial(servicioEditorial);
        agregar.setVisible(true);
    }//GEN-LAST:event_itemAgregarEActionPerformed

    private void itemListarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarEActionPerformed
        // TODO add your handling code here:
        ListarEditoriales listar = new ListarEditoriales(servicioEditorial);
        listar.setVisible(true);
    }//GEN-LAST:event_itemListarEActionPerformed

    private void itemActualizarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarLActionPerformed
        ActualizarLibro actualizar = new ActualizarLibro(servicioPublicacion);
        actualizar.setVisible(true);
    }//GEN-LAST:event_itemActualizarLActionPerformed

    private void itemActualizarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarRActionPerformed
        // TODO add your handling code here:
        ActualizarRevista actualizar = new ActualizarRevista(servicioPublicacion);
        actualizar.setVisible(true);
    }//GEN-LAST:event_itemActualizarRActionPerformed

    private void itemBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEActionPerformed
        // TODO add your handling code here:
        BuscarEditorial buscar = new BuscarEditorial(servicioPublicacion);
        buscar.setVisible(true);
    }//GEN-LAST:event_itemBuscarEActionPerformed

    private void itemActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarEActionPerformed
        // TODO add your handling code here:
        ActualizarEditorial actualizar = new ActualizarEditorial(servicioPublicacion);
        actualizar.setVisible(true);
    }//GEN-LAST:event_itemActualizarEActionPerformed

    private void itemEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEActionPerformed
        // TODO add your handling code here:
        EliminarEditorial eliminar = new EliminarEditorial(servicioPublicacion);
        eliminar.setVisible(true);
    }//GEN-LAST:event_itemEliminarEActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        // TODO add your handling code here:
        InfoEmpresa info = new InfoEmpresa();
        info.setVisible(true);
    }//GEN-LAST:event_menuInfoActionPerformed

    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnCerrar;
    private javax.swing.JMenuItem itemActualizarE;
    private javax.swing.JMenuItem itemActualizarL;
    private javax.swing.JMenuItem itemActualizarR;
    private javax.swing.JMenuItem itemAgregarE;
    private javax.swing.JMenuItem itemAgregarL;
    private javax.swing.JMenuItem itemAgregarR;
    private javax.swing.JMenuItem itemBuscarE;
    private javax.swing.JMenuItem itemBuscarL;
    private javax.swing.JMenuItem itemBuscarR;
    private javax.swing.JMenuItem itemCalcularL;
    private javax.swing.JMenuItem itemCalcularR;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemEliminarE;
    private javax.swing.JMenuItem itemEliminarR;
    private javax.swing.JMenuItem itemListarE;
    private javax.swing.JMenuItem itemListarL;
    private javax.swing.JMenuItem itemListarR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImagenLogo;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenu menuLibro;
    private javax.swing.JMenu menuRevista;
    // End of variables declaration//GEN-END:variables
}
