/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.feliperyjuanr.view;

import com.feliperyjuanr.services.ServicioPublicaciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanp
 */
public class ListarRevistas extends javax.swing.JFrame implements IRevistaInteresada {
    private ServicioPublicaciones servicioPublicacion;

    /**
     * Creates new form ListarRevistas
     */
    public ListarRevistas(ServicioPublicaciones servicioPublicacion) {
        this.servicioPublicacion = servicioPublicacion;
        servicioPublicacion.addInteresadaC(this);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void cambioRevista()
    {
        DefaultTableModel model = (DefaultTableModel) tblRevistas.getModel();
        model.setRowCount(0);
        
        for (int i = 0; i < servicioPublicacion.listarRevistas().size(); i++) 
        {
            model.addRow(new Object[]{
                servicioPublicacion.listarRevistas().get(i).getTitulo(),
                servicioPublicacion.listarRevistas().get(i).getAutor(),
                servicioPublicacion.listarRevistas().get(i).getPrecio(),
                servicioPublicacion.listarRevistas().get(i).calcularPrecio(),
                servicioPublicacion.listarRevistas().get(i).getVolumen(),
                servicioPublicacion.listarRevistas().get(i).estaSuscrito()
            });
        }
    }
    
    @Override
    public void dispose()
    {
        servicioPublicacion.deleteInteresadaC(this);
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLibrosPublicados = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRevistas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Revistas");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(156, 39, 176), 2, true));

        lblLibrosPublicados.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblLibrosPublicados.setForeground(new java.awt.Color(156, 39, 176));
        lblLibrosPublicados.setText("Revistas Publicadas");

        btnListar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tblRevistas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(156, 39, 176), 1, true));
        tblRevistas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tblRevistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Precio Base", "Precio Final", "Volumen", "Suscrito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRevistas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLibrosPublicados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLibrosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblRevistas.getModel();
        model.setRowCount(0);
        
        if(servicioPublicacion.listarRevistas().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Error: No hay Revistas para mostrar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        for (int i = 0; i < servicioPublicacion.listarRevistas().size(); i++) {
            
            model.addRow(new Object[]{
                servicioPublicacion.listarRevistas().get(i).getTitulo(),
                servicioPublicacion.listarRevistas().get(i).getAutor(),
                servicioPublicacion.listarRevistas().get(i).getPrecio(),
                servicioPublicacion.listarRevistas().get(i).calcularPrecio(),
                servicioPublicacion.listarRevistas().get(i).getVolumen(),
                servicioPublicacion.listarRevistas().get(i).estaSuscrito()
            });
        }
        }
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLibrosPublicados;
    private javax.swing.JTable tblRevistas;
    // End of variables declaration//GEN-END:variables
}
